sudo: required
dist: trusty
language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.m2/repository"

before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

install:
 - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

script:
  - mvn cobertura:cobertura -B

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: .travis/deploy.sh
    skip_cleanup: true
    on:
      tags: true
