sudo: required
dist: trusty
language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2/repository"

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)

script: mvn clean cobertura:cobertura