= Contaistner image:https://travis-ci.org/snapitch/contaistner.svg?branch=master["Build Status", link="https://travis-ci.org/snapitch/contaistner"] image:https://codecov.io/github/snapitch/contaistner/coverage.svg?branch=master["Code coverage", link="image::https://codecov.io/github/snapitch/contaistner"]

`contaistner` makes easy to launch Docker containers in Spring Boot integration tests.

Principal features are :

* run containers only from existing images container. No build or docker-compose.
* provides mechanism to manage automatic ports bindings by generating properties.
* links containers lifecycle to Spring application context lifecycle

== Installation and getting started

Add this dependency to your project. For exemple, in maven pom file :

[source,xml]
----
<dependency>
    <groupId>org.snapitch</groupId>
    <artifactId>contaistner</artifactId>
    <version>0.0.1-SNAPSHOT</version>
</dependency>
----

By default, `spring-boot-docker` use two yamls for configuration :

* `application-<active-profile>.yml` describe containers to launch with configuration inspired by `docker-compose` yaml syntax
* `application-contaistner.yml` contains applicative properties that depends on containers data

For example, to start a redis and expose port 6379 :

.IntegrationTest.java
[source,java]
----
@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test") // <1>
public class IntegrationTest {

    @Test
    public void myTest() {
        ...
    }
}
----
<1> Active profile in order to load contaistner boostrap properties

.application-test.yml
[source,yaml]
----
contaistner:
  serivces:
    redis:
      image: redis:latest
      ports: 6379/tcp
----

And the applicative configuration can reference binding ports if you use this configuration :

.application-contaistner.yml
[source,yaml]
----
spring:
  redis:
    port: ${contaistner.services.redis.bindings.6379/tcp} // <1>
----
<1> Retrieve port binding automatically assign by docker of container port 6379.
If docker binds container port 6379 to host port 32567, value of `spring.redis.port` will be `32567`.

If docker binds container port 6379 to host port 32567, value of `spring.redis.port` will be `32567`.

== Configuration of container

Each container can be configure by properties.
It is properties prefixed by `contaistner.services.<containerKey>` and is inspired by `docker-compose` yaml syntax.

|===
|Name |Description |Generated | Example

|`id`
|Container identifier (uuid)
|yes
|`f2276208f749`

|`name`
|Container name
|yes
|`inspiring_edison`

|`image`
|Specify the image to start the container from. Can either be a repository/tag or a partial image ID. Identical to docker-compose
|no
|`redis:latest`

|`ports`
|Expose ports. Like to docker-compose
|no
|`6379`, `6379/tcp`

|`bindings.<port>`
|Bindings of container ports to host ports
|yes
|`bindings.6379/tcp` = `32567`

|`environment`
|Add environment variables. Identical to docker-compose
|no
|

|`entrypoint`
|Override the default entrypoint. Identical to docker-compose
|no
|

|`tmpfs`
|Mount a temporary file system inside the container. Can be a single value or a list. Identical to docker-compose
|no
|`/run`, `/tmp`
|===

== Configuration examples

=== In memory Postgres

.application-bootstrap-contaistner.yml
[source,yaml]
----
include::src/test/resources/application-postgres-bootstrap-contaistner.yml[]
----

.application-contaistner.yml
[source,yaml]
----
include::src/test/resources/application-postgres-contaistner.yml[]
----
